apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-service-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true" 
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - na-allocator.apps.slc.net
    secretName: slc-net-tls 
  rules:
  - host: na-allocator.apps.slc.net
    http:
      paths:
        - path: /api # hmmm
          pathType: Prefix
          backend:
            service:
              name: na-schedule-allocator-backend-service
              port:
                number: 80 